### ISSUE TITLE
Использование устаревшей функции gui.HideGameUI

### ISSUE THREAD

**Issue by Umoritelno** [Sh1ro-Sam4/_horde#2]
https://github.com/Sh1ro-Sam4/_horde/blob/510c0a6dcf751083d55757275ab76d615923d3d3/addons/shiz-addons/lua/shizlib-addons/chat/chat_cl.lua#L501-L504
![Снимок экрана 2024-10-16 204442](https://github.com/user-attachments/assets/adbeba37-8d87-4ba1-a432-079d5d0add3e)

**Comment by Umoritelno** [comment]
https://github.com/user-attachments/assets/2ecc7854-b591-4165-990f-23d865261b14

Терь полностью блокается открытие главного меню
Мне кажется надо проверку на эту переменную добавить
https://github.com/Sh1ro-Sam4/_horde/blob/510c0a6dcf751083d55757275ab76d615923d3d3/addons/shiz-addons/lua/shizlib-addons/chat/chat_cl.lua#L1023

**Comment by Sh1ro-Sam4** [comment]
исправлено
